name: Lint

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  pull_request:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Lint
        run: helm lint --strict -f test-values.yaml
        working-directory: charts/test

  conform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Generate manifests
        run: helm template . -f test-values.yaml > _manifests.yaml
        working-directory: charts/test

      - name: Conformence check
        uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          entrypoint: '/kubeconform'
          args: "-strict -summary charts/test/_manifests.yaml"
